name: Deploy

on:
  push:
    branches:
      - master
      - dev
      - feature/build-staging

jobs:
  staging:
    runs-on: ubuntu-latest
    name: Staging Deploy
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/feature/build-staging'
    steps:
      - name: ssh pipelines
        uses: appleboy/ssh-action@master
        env:
          WELCOME: "Staging Deploy"
        with:
          host: '${{ secrets.SSH_HOST }}'
          username: '${{ secrets.SSH_USER }}'
          password: '${{ secrets.SSH_PASSWORD }}'
          port: 22
          debug: true
          script: |
            echo "Adding SSH Key"
            eval "$(ssh-agent -s)"
            ssh-add -k ~/.ssh/deploy_aibq_api

            echo "Pulling repository..."
            cd ~/api.aibq.qc.ca
            git pull origin dev

            echo "Composer..."
            cd src
            ~/.phpenv/shims/php ~/composer.phar install --prefer-dist --no-scripts -o
            ~/.phpenv/shims/php ~/composer.phar dumpautoload

            echo "Artisan..."
            ~/.phpenv/shims/php artisan config:cache
            ~/.phpenv/shims/php artisan migrate

  master:
    runs-on: ubuntu-latest
    name: Prod Deploy
    if: github.ref == 'refs/heads/master'
    steps:
      - name: ssh pipelines
        uses: appleboy/ssh-action@master
        env:
          WELCOME: "Prod Deploy"
        with:
          host: '${{ secrets.SSH_HOST }}'
          username: '${{ secrets.SSH_USER }}'
          password: '${{ secrets.SSH_PASSWORD }}'
          port: 22
          debug: true
          script: |
            echo "Adding SSH Key"
            eval "$(ssh-agent -s)"
            ssh-add -k ~/.ssh/deploy_aibq_api

            echo "Pulling repository..."
            cd ~/api.aibq.qc.ca
            git pull origin master

            echo "Composer..."
            cd src
            ~/.phpenv/shims/php ~/composer.phar install --prefer-dist --no-scripts -o
            ~/.phpenv/shims/php ~/composer.phar dumpautoload

            echo "Artisan..."
            ~/.phpenv/shims/php artisan config:cache
            ~/.phpenv/shims/php artisan migrate:status
